# ARG ALPINE_VERSION=3.17.3
# ARG OPENSSL_VERSION=1.1.1k
ARG ALPINE_VERSION=3.17.3
ARG OPENSSL_VERSION=3.0.8-r3

FROM alpine:${ALPINE_VERSION} AS openssl
ARG OPENSSL_VERSION

RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache openssl=${OPENSSL_VERSION}

ENTRYPOINT [ "openssl" ]